/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as UserUserIdImport } from "./routes/user/$userId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const UserUserIdRoute = UserUserIdImport.update({
  path: "/user/$userId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/user/$userId": {
      id: "/user/$userId";
      path: "/user/$userId";
      fullPath: "/user/$userId";
      preLoaderRoute: typeof UserUserIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/user/$userId": typeof UserUserIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/user/$userId": typeof UserUserIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/user/$userId": typeof UserUserIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/user/$userId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/user/$userId";
  id: "__root__" | "/" | "/user/$userId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  UserUserIdRoute: typeof UserUserIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserUserIdRoute: UserUserIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/user/$userId": {
      "filePath": "user/$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
