# Reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# Reference: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install package
        run: npm ci

      - name: Check format and lint code
        run: npm run format:check && npm run lint

      - name: Build project
        run: npm run build --if-present
